version: '3.9'

services:
  postgresql:
    restart: always
    image: 'postgres:16.7'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - psql-data:/var/lib/postgresql/data

volumes:
  psql-data: