#!/bin/bash

psql -U $ROOT_USER_PSQL -p $DB_PORT -h $LHOST \
    -c "CREATE ROLE $USER_PRODUCT_SERVICE WITH PASSWORD '$PASSWORD_PRODUCT_SERVICE';"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $LHOST \
    -c "CREATE DATABASE $DB_PRODUCT_SERVICE;"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $LHOST \
    -c "ALTER ROLE $USER_PRODUCT_SERVICE WITH LOGIN;"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $LHOST \
    -c "GRANT ALL PRIVILEGES ON DATABASE $DB_PRODUCT_SERVICE TO $USER_PRODUCT_SERVICE;"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $LHOST \
    -c "GRANT pg_write_server_files TO $USER_PRODUCT_SERVICE;"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $LHOST \
    -c "GRANT pg_read_server_files TO $USER_PRODUCT_SERVICE;"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $LHOST \
    -c "GRANT CREATE ON SCHEMA public TO product_service;"
psql -U $ROOT_USER_PSQL -p $DB_PORT -h $LHOST \
    -c "ALTER USER $USER_PRODUCT_SERVICE WITH SUPERUSER;"
PGPASSWORD=$PASSWORD_PRODUCT_SERVICE psql -U $USER_PRODUCT_SERVICE -p $DB_PORT -h $LHOST \
    -c 'CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);'